schema: ./graphql/schema.graphql
documents: 'graphql/*.gql'
generates:

extensions:
  endpoints:
#    development:
#      url: "http://localhost:8060/graphql"
#      introspect: true
    prod:
      url: "https://emd.utcluj.ro/graphql"
      introspect: true